version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/terraforming
    steps:
      - checkout
      - run:
          name: "terraform init"
          command: |
            terraform init -input=false
      - run:
          name: "check terraform format"
          command: |
            terraform plan
  deploy:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/AWSTerraform
    steps:
      - checkout
      - run:
          name: "terraform init"
          command: |
            terraform init -input=false
      - run:
          name: "terraform apply"
          command: |
            terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
